name = "OnesZeros"
defaultTargets = ["OnesZeros", "OnesZerosMathlib"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.22.0"

[[lean_lib]]
name = "OnesZeros"

[[lean_lib]]
name = "OnesZerosMathlib"
